### ISSUE TITLE
VS2022: Doesnt work in debug but in release mode

### ISSUE THREAD

**Issue by 29th-Day** [amhndu/SimpleNES#29] opened 2022-06-01 12:10 UTC
I imported the source into a visual studio 2022 solution and fixed any compiler errors. Now I can compile the program in debug and release mode, but debug mode either barely runs or throws runtime errors. However, everything works in release mode. Any suggestions where the problem could be?

**Comment by SuzieQQ** [comment] 2022-06-04 22:41
which one did you fill in? because I had a block in the version with the sound that I posted in my github in the debug mode

in this version no problem here

**Comment by amhndu** [comment] 2022-08-08 14:36
Can you run it with an active debugger? A stack trace would be very helpful. Please also pull the latest changes

**Comment by amhndu** [comment] 2022-08-21 15:22
I've played SMB many times with the emulator and tried at least the beginning part of LoZ many times, this has never happened. I'm sorry but I'll have to close this as I can't reproduce.

**Closed by amhndu** 2022-08-21 15:22 UTC

**Comment by mediaexplorer74** [comment] 2022-10-29 09:24
> l studio 2022 solution and fixed any compiler errors. Now I can compile the program in debug and release mode, but debug mode either barely runs or throws runtime errors. However, everything works in release mode. Any suggestions where the problem could be?

Can you share your SimpleNES fork (with .sln solution)?
